/**
 * Interfaz que se encarga de matricular los estudiantes
 */
package vista;

import controlador.ControlMatricula;
import modelo.Registro;
import modelo.RegistroCursos;
import modelo.RegistroMatricula;

/**
 *
 * @author vini
 */
public class GUIEMatriculas  extends javax.swing.JFrame{

    private Registro registroEstudiantes;
    private RegistroCursos registroCursos;
    private RegistroMatricula registroMatricula;
    private ControlMatricula controlMatricula;

    /**
     * Creates new form GUIEMatriculas
     */
    public GUIEMatriculas(Registro registroEstudiante, RegistroCursos registroCursos,
            RegistroMatricula registroMatricula1, GUIECursos gUIECursos, GUIEstudiantes gUIEstudiantes, GUISIRES guisires) {

        this.registroCursos = registroCursos;
        this.registroEstudiantes = registroEstudiante;
        this.registroMatricula = registroMatricula1;
        initComponents();
        panelMatriculas1.agregarItemsComboBox(registroCursos);
        controlMatricula = new ControlMatricula(registroEstudiante, registroCursos, registroMatricula, this, panelMatriculas1, gUIECursos, gUIEstudiantes, guisires);

        panelMatriculas1.escucharMatricula(controlMatricula);
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMatriculas1 = new vista.PanelMatriculas();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sistema de Matriculas");
        setBounds(new java.awt.Rectangle(400, 250, 0, 0));
        setResizable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelMatriculas1, javax.swing.GroupLayout.DEFAULT_SIZE, 1219, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMatriculas1, javax.swing.GroupLayout.PREFERRED_SIZE, 590, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private vista.PanelMatriculas panelMatriculas1;
    // End of variables declaration//GEN-END:variables

}
