/**
 * Interfas que muestra el informe de Cursos agregados
 */
package vista;

import java.awt.event.MouseListener;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vini
 */
public class GUIEInformeCursos extends javax.swing.JFrame {

    /**
     * Creates new form GUIEInformeCursos
     */
    public GUIEInformeCursos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablaCursos = new javax.swing.JTable();
        jBTNAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Informe");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Droid Sans Fallback", 3, 18)); // NOI18N
        jLabel1.setText("Informe");

        jTablaCursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nobre", "Siglas", "Creditos"
            }
        ));
        jTablaCursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablaCursosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablaCursos);

        jBTNAtras.setText("Atras");
        jBTNAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTNAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBTNAtras, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBTNAtras)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBTNAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTNAtrasActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBTNAtrasActionPerformed

    /**
     * 
     * @param evt 
     */
    private void jTablaCursosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablaCursosMouseClicked
        String salida = "Nombre:  " + jTablaCursos.getValueAt(jTablaCursos.getSelectedRow(), 0) + "\n"
                + "Siglas:  " + jTablaCursos.getValueAt(jTablaCursos.getSelectedRow(), 1)
                + "\nCreditos:  " + jTablaCursos.getValueAt(jTablaCursos.getSelectedRow(), 2);
        JOptionPane.showMessageDialog(null, salida);
    }//GEN-LAST:event_jTablaCursosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBTNAtras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablaCursos;
    // End of variables declaration//GEN-END:variables

    /**
     * 
     * @param datosFilas
     * @param etiquetas 
     */
    public void setValores(String[][] datosFilas, String etiquetas[]) {
        if (datosFilas != null) {
            jTablaCursos.setModel(new DefaultTableModel(datosFilas, etiquetas));
            jScrollPane1.setViewportView(jTablaCursos);
        }
    }

    ///////////////////////////////////////////////////////////////////////////
    /**
     * 
     * @param controlador 
     */
    public void escucharTabla(MouseListener controlador) {
        jTablaCursos.addMouseListener(controlador);
    }

}
