/**
 * Interfaz para agregar cursos
 */
package vista;

import controlador.ControlCursos;
import modelo.RegistroCursos;

/**
 *
 * @author vini
 */
public class GUIECursos extends javax.swing.JFrame {

    private ControlCursos controlCursos;
    private RegistroCursos registroCursos;

//-----------------------------------------------------------------
   /**
    * 
    * @param registroCursos 
    */
    public GUIECursos(RegistroCursos registroCursos) {
        this.registroCursos = registroCursos;
        initComponents();
        controlCursos = new ControlCursos(registroCursos, this, panelCursos1);
        panelCursos1.escucharBotonesCursos(controlCursos);
        this.setLocationRelativeTo(null);
    }
//-----------------------------------------------------------------

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCursos1 = new vista.PanelCursos();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sistemas de Registros de Estudiantes (SIRES)");
        setBounds(new java.awt.Rectangle(250, 250, 0, 0));
        setResizable(false);

        panelCursos1.setBackground(new java.awt.Color(126, 195, 194));
        panelCursos1.setAlignmentX(250.0F);
        panelCursos1.setAlignmentY(250.0F);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelCursos1, javax.swing.GroupLayout.PREFERRED_SIZE, 722, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCursos1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private vista.PanelCursos panelCursos1;
    // End of variables declaration//GEN-END:variables
}
