/**
 * Ventana donde se agregan los paneles para el registro de estudiantes
 */
package vista;

import controlador.ControlEstudiante;
import javax.swing.JOptionPane;
import modelo.Registro;

/**
 *
 * @author vini
 */
public class GUIEstudiantes extends javax.swing.JFrame {

        
    public ControlEstudiante controlEstudiante;
    private Registro registroEst;
    
    /**
     * Creates new form GUIEstudiantes
     */
    public GUIEstudiantes(Registro registroEstudiantes) {
        registroEst = registroEstudiantes;
        initComponents();
        controlEstudiante = new ControlEstudiante(panelEstudiante1, panelBotones1, registroEst, this);
        panelBotones1.escuchar(controlEstudiante);
        panelEstudiante1.escucharConsulta(controlEstudiante);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBotones1 = new vista.PanelBotones();
        panelEstudiante1 = new vista.PanelEstudiante();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sistemas de Registros de Estudiantes (SIRES)");
        setBounds(new java.awt.Rectangle(300, 200, 0, 0));
        setResizable(false);

        panelBotones1.setBackground(new java.awt.Color(126, 195, 194));

        panelEstudiante1.setBackground(new java.awt.Color(126, 195, 194));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelEstudiante1, javax.swing.GroupLayout.DEFAULT_SIZE, 732, Short.MAX_VALUE)
                    .addComponent(panelBotones1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(panelEstudiante1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelBotones1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private vista.PanelBotones panelBotones1;
    private vista.PanelEstudiante panelEstudiante1;
    // End of variables declaration//GEN-END:variables

    /**
     * 
     * @param mensaje 
     */
    public static void mensaje (String mensaje) {
        JOptionPane.showMessageDialog(null, mensaje);
    }

}
