/**
 * Interfas que muestra el informe de estudiantes agregados
 */
package vista;

import java.awt.event.MouseListener;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vini
 */
public class GUIEInforme extends javax.swing.JFrame {

    /**
     * Creates new form GUIEInforme
     */
    public GUIEInforme() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barraDesplazamiento = new javax.swing.JScrollPane();
        jTabla = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Informe");
        setResizable(false);

        jTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Carnet", "Nombre", "Edad"
            }
        ));
        jTabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablaMouseClicked(evt);
            }
        });
        barraDesplazamiento.setViewportView(jTabla);

        jLabel1.setFont(new java.awt.Font("Droid Sans Fallback", 3, 18)); // NOI18N
        jLabel1.setText("Reporte ");

        jButton1.setText("Atras");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(barraDesplazamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(158, 158, 158)
                                .addComponent(jLabel1)))
                        .addGap(0, 1, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addComponent(barraDesplazamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablaMouseClicked
        String salida = "Carnet:  "+jTabla.getValueAt(jTabla.getSelectedRow(), 0)+"\n"+
                "Nombre:  "+jTabla.getValueAt(jTabla.getSelectedRow(), 1)+
                "\nEdad:  "+jTabla.getValueAt(jTabla.getSelectedRow(), 2);
        
        JOptionPane.showMessageDialog(null, salida);
    }//GEN-LAST:event_jTablaMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane barraDesplazamiento;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTable jTabla;
    // End of variables declaration//GEN-END:variables

    /**
     * 
     * @param datosFilas
     * @param etiquetas 
     */
    public void setValores(String[][] datosFilas, String etiquetas[]) {
        if (datosFilas != null) {
            jTabla.setModel(new DefaultTableModel(datosFilas, etiquetas));
            barraDesplazamiento.setViewportView(jTabla);
        }
    }
    
    ///////////////////////////////////////////////////////////////////////////
    /**
     * 
     * @return String []
     */
    public String [] getdatosFila () {
        String datos [] = new String [jTabla.getColumnCount()];
        int filaSeleccionada = jTabla.getSelectedRow();
        
        for (int columna = 0; columna<datos.length; columna++) {
            datos [columna] = (String) jTabla.getValueAt(filaSeleccionada, columna);
        }
        return datos;
    }
    
    ///////////////////////////////////////////////////////////////////////////
    /**
     * 
     * @param controlador 
     */
    public void escucharTabla (MouseListener controlador) {
        jTabla.addMouseListener(controlador);
    }
    
}
