/**
 * Muestra un informe de los estudiantes y los cursos que matriculó
 */
package vista;

import controlador.ControlReporteMatricula;
import modelo.RegistroMatricula;

/**
 *
 * @author vini
 */
public class GUIEReporteMatricula extends javax.swing.JFrame {

    private ControlReporteMatricula controlReporteMatricula;
    private RegistroMatricula registroMatricula;

    /**
     * Creates new form GUIEReporteMatricula
     */
    public GUIEReporteMatricula(RegistroMatricula registroMatricular) {
        initComponents();
        this.registroMatricula = registroMatricular;
        controlReporteMatricula = new ControlReporteMatricula(panelReporteMatricula1, registroMatricula, this);
        panelReporteMatricula1.escucharBotones(controlReporteMatricula);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelReporteMatricula1 = new vista.PanelReporteMatricula();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Informe");
        setResizable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelReporteMatricula1, javax.swing.GroupLayout.DEFAULT_SIZE, 753, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelReporteMatricula1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private vista.PanelReporteMatricula panelReporteMatricula1;
    // End of variables declaration//GEN-END:variables
}
