/**
 * Ventana principal, donde se crean todas las demas ventanas
 */
package vista;

import controlador.ControlSIRES;
import java.awt.event.ActionListener;

/**
 *
 * @author vini
 */
public class GUISIRES extends javax.swing.JFrame {

    /**
     * Creates new form GUISIRES
     */
    public GUISIRES() {
        initComponents();
        this.setResizable(false);
        ControlSIRES control = new ControlSIRES(this);
        this.escucharMenuItem(control);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mbSIRES = new javax.swing.JMenuBar();
        mnArchivo = new javax.swing.JMenu();
        mniSalir = new javax.swing.JMenuItem();
        mnRegistro = new javax.swing.JMenu();
        mniRegistroEstudiantes = new javax.swing.JMenuItem();
        mniRegistroCursos = new javax.swing.JMenuItem();
        jMenuItem_Matricula = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemInformeMatricula = new javax.swing.JMenuItem();
        jMenuItem_Tabla_Estudiante = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistemas de Registros de Estudiantes (SIRES)");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setResizable(false);

        mnArchivo.setText("Archivo");

        mniSalir.setText("Salir");
        mniSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSalirActionPerformed(evt);
            }
        });
        mnArchivo.add(mniSalir);

        mbSIRES.add(mnArchivo);

        mnRegistro.setText("Registro");

        mniRegistroEstudiantes.setText("Registro Estudiantes");
        mniRegistroEstudiantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniRegistroEstudiantesActionPerformed(evt);
            }
        });
        mnRegistro.add(mniRegistroEstudiantes);

        mniRegistroCursos.setText("Registro Cursos");
        mniRegistroCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniRegistroCursosActionPerformed(evt);
            }
        });
        mnRegistro.add(mniRegistroCursos);

        jMenuItem_Matricula.setText("Sistema de matriculas");
        jMenuItem_Matricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_MatriculaActionPerformed(evt);
            }
        });
        mnRegistro.add(jMenuItem_Matricula);

        mbSIRES.add(mnRegistro);

        jMenu1.setText("Informes");

        jMenuItemInformeMatricula.setText("Informe de matricula");
        jMenu1.add(jMenuItemInformeMatricula);

        jMenuItem_Tabla_Estudiante.setText("Mostrar tabla de Estudiante");
        jMenu1.add(jMenuItem_Tabla_Estudiante);

        mbSIRES.add(jMenu1);

        setJMenuBar(mbSIRES);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 483, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 159, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mniSalirActionPerformed

    private void mniRegistroEstudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniRegistroEstudiantesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mniRegistroEstudiantesActionPerformed

    private void mniRegistroCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniRegistroCursosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mniRegistroCursosActionPerformed

    private void jMenuItem_MatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_MatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem_MatriculaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUISIRES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUISIRES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUISIRES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUISIRES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUISIRES().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItemInformeMatricula;
    private javax.swing.JMenuItem jMenuItem_Matricula;
    private javax.swing.JMenuItem jMenuItem_Tabla_Estudiante;
    private javax.swing.JMenuBar mbSIRES;
    private javax.swing.JMenu mnArchivo;
    private javax.swing.JMenu mnRegistro;
    private javax.swing.JMenuItem mniRegistroCursos;
    private javax.swing.JMenuItem mniRegistroEstudiantes;
    private javax.swing.JMenuItem mniSalir;
    // End of variables declaration//GEN-END:variables

    public static final String MNI_SALIR = "Salir";
    public static final String MNI_REGISTRO_ESTUDIANTES = "Registro Estudiantes";
    public static final String MNI_REGISTRO_CURSOS = "Registro Cursos";
    public static final String MNI_SISTEMA_MATRICULAS = "Sistema de matriculas";
    public static final String MNI_INFORME_MATRICULA = "Informe de matricula";
    public static final String MNI_TABLA_ESTUDIANTE = "Mostrar tabla de Estudiante";
    
    /**
     * 
     * @param control 
     */
    public void escucharMenuItem(ActionListener control) {
        this.mniSalir.addActionListener(control);
        this.mniRegistroEstudiantes.addActionListener(control);
        this.mniRegistroCursos.addActionListener(control);
        this.jMenuItem_Matricula.addActionListener(control);  
        this.jMenuItemInformeMatricula.addActionListener(control);
        this.jMenuItem_Tabla_Estudiante.addActionListener(control);
    }
    
}
