/**
 * panel cursos de la ventana GUIECursos
 */
package vista;

import controlador.ControlCursos;


/**
 *
 * @author vini
 */
public class PanelCursos extends javax.swing.JPanel {

    /**
     * Creates new form PanelCursos
     */
    public PanelCursos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTxtCursos_nombre = new javax.swing.JTextField();
        jTxtCursos_Siglas = new javax.swing.JTextField();
        jTxtCursos_Creditos = new javax.swing.JTextField();
        jBTNBuscarPorSiglas = new javax.swing.JButton();
        jBTNConsultarCursos = new javax.swing.JButton();
        jBtnAtrasCursos = new javax.swing.JButton();
        jBTNAgregarCurso = new javax.swing.JButton();
        jBTNModificarCurso = new javax.swing.JButton();
        jBTNEliminarCurso = new javax.swing.JButton();

        setBackground(new java.awt.Color(167, 172, 236));

        jLabel1.setFont(new java.awt.Font("Droid Sans Fallback", 3, 22)); // NOI18N
        jLabel1.setText("Registro cursos");

        jLabel2.setFont(new java.awt.Font("Droid Sans Fallback", 1, 13)); // NOI18N
        jLabel2.setText("Nombre del curso:");

        jLabel3.setFont(new java.awt.Font("Droid Sans Fallback", 1, 13)); // NOI18N
        jLabel3.setText("Siglas del curso:");

        jLabel4.setFont(new java.awt.Font("Droid Sans Fallback", 1, 13)); // NOI18N
        jLabel4.setText("Cantidad de creditos:");

        jTxtCursos_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCursos_nombreActionPerformed(evt);
            }
        });

        jTxtCursos_Creditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCursos_CreditosActionPerformed(evt);
            }
        });
        jTxtCursos_Creditos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtCursos_CreditosKeyTyped(evt);
            }
        });

        jBTNBuscarPorSiglas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1426204169_xmag.png"))); // NOI18N
        jBTNBuscarPorSiglas.setText("Buscar");

        jBTNConsultarCursos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1427791644_Zoom In.png"))); // NOI18N
        jBTNConsultarCursos.setText("Consultar");
        jBTNConsultarCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTNConsultarCursosActionPerformed(evt);
            }
        });

        jBtnAtrasCursos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1427101796_back.png"))); // NOI18N
        jBtnAtrasCursos.setText("Atras");

        jBTNAgregarCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1427791562_Add.png"))); // NOI18N
        jBTNAgregarCurso.setText("Agregar");

        jBTNModificarCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1426203706_sign-up.png"))); // NOI18N
        jBTNModificarCurso.setText("Modificar");
        jBTNModificarCurso.setEnabled(false);
        jBTNModificarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTNModificarCursoActionPerformed(evt);
            }
        });

        jBTNEliminarCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1427791599_Delete.png"))); // NOI18N
        jBTNEliminarCurso.setText("Eliminar");
        jBTNEliminarCurso.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jBTNAgregarCurso)
                .addGap(18, 18, 18)
                .addComponent(jBTNModificarCurso)
                .addGap(18, 18, 18)
                .addComponent(jBTNEliminarCurso)
                .addGap(18, 18, 18)
                .addComponent(jBTNConsultarCursos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                .addComponent(jBtnAtrasCursos)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jTxtCursos_Siglas)
                                    .addGap(18, 18, 18)
                                    .addComponent(jBTNBuscarPorSiglas))
                                .addComponent(jTxtCursos_nombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addComponent(jLabel1))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtCursos_Creditos, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTxtCursos_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTxtCursos_Siglas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBTNBuscarPorSiglas))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTxtCursos_Creditos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBTNAgregarCurso)
                    .addComponent(jBTNModificarCurso)
                    .addComponent(jBTNEliminarCurso)
                    .addComponent(jBTNConsultarCursos)
                    .addComponent(jBtnAtrasCursos))
                .addGap(52, 52, 52))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtCursos_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCursos_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCursos_nombreActionPerformed

    private void jBTNConsultarCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTNConsultarCursosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBTNConsultarCursosActionPerformed

    private void jBTNModificarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTNModificarCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBTNModificarCursoActionPerformed

    private void jTxtCursos_CreditosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtCursos_CreditosKeyTyped
        char tipoEntrada = evt.getKeyChar();
        if (tipoEntrada < '0' || tipoEntrada > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_jTxtCursos_CreditosKeyTyped

    private void jTxtCursos_CreditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCursos_CreditosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCursos_CreditosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBTNAgregarCurso;
    private javax.swing.JButton jBTNBuscarPorSiglas;
    private javax.swing.JButton jBTNConsultarCursos;
    private javax.swing.JButton jBTNEliminarCurso;
    private javax.swing.JButton jBTNModificarCurso;
    private javax.swing.JButton jBtnAtrasCursos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTxtCursos_Creditos;
    private javax.swing.JTextField jTxtCursos_Siglas;
    private javax.swing.JTextField jTxtCursos_nombre;
    // End of variables declaration//GEN-END:variables

    /**
     * 
     * ************* metodos sets & gets ************
     */
    public int getjTxtCursos_Creditos() {
        if (jTxtCursos_Creditos.getText().equalsIgnoreCase("")) {
        return 0;
        }
        int valor = Integer.parseInt(this.jTxtCursos_Creditos.getText());
        return valor;
    }

    public void setjTxtCursos_Creditos(String jTxtCursos_Creditos) {
        this.jTxtCursos_Creditos.setText(jTxtCursos_Creditos);
    }

    public String getjTxtCursos_Siglas() {
        return this.jTxtCursos_Siglas.getText().toString().trim();
    }

    public void setjTxtCursos_Siglas(String jTxtCursos_Siglas) {
        this.jTxtCursos_Siglas.setText(jTxtCursos_Siglas);
    }

    public String getjTxtCursos_nombre() {
        return this.jTxtCursos_nombre.getText().toString().trim();
    }

    public void setjTxtCursos_nombre(String jTxtCursos_nombre) {
        this.jTxtCursos_nombre.setText(jTxtCursos_nombre);
    }

    
    
    
    public static final String BTNAGREGAR_CURSOS = "Agregar";
    public static final String BTNBUSCAR_CURSOS = "Buscar";
    public static final String BTNMODIFICAR_CURSOS = "Modificar";
    public static final String BTNELIMINAR_CURSOS = "Eliminar";
    public static final String BTNCONSULTAR_CURSOS = "Consultar";
    public static final String BTNATRAS_CURSOS = "Atras";
    
    /**
     * 
     * @param control 
     */
    public void escucharBotonesCursos (ControlCursos control) {
        this.jBTNAgregarCurso.addActionListener(control);
        this.jBTNBuscarPorSiglas.addActionListener(control);
        this.jBTNConsultarCursos.addActionListener(control);
        this.jBtnAtrasCursos.addActionListener(control);
        this.jBTNModificarCurso.addActionListener(control);
        this.jBTNEliminarCurso.addActionListener(control);
    }
    
    /**
     * 
     * @param estado 
     */
    public void enableButtons (boolean estado){
        this.jBTNModificarCurso.setEnabled(estado);
        this.jBTNEliminarCurso.setEnabled(estado);
    }
    
    /**
     * 
     */
    public void limpiar () {
        this.jTxtCursos_nombre.setText("");
        this.jTxtCursos_Siglas.setText("");
        this.jTxtCursos_Creditos.setText("");
    }
}