/**
 * Panel botones de la ventana GUIEEstudiantes
 */
package vista;

import controlador.ControlEstudiante;


/**
 *
 * @author vini
 */
public class PanelBotones extends javax.swing.JPanel {

    /**
     * Creates new form PanelBotones
     */
    public PanelBotones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JbAgregar = new javax.swing.JButton();
        jBModificar = new javax.swing.JButton();
        jBConsultar = new javax.swing.JButton();
        jBEliminar = new javax.swing.JButton();
        jBSalir = new javax.swing.JButton();

        setBackground(new java.awt.Color(170, 196, 219));

        JbAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1426203534_Add-Male-User.png"))); // NOI18N
        JbAgregar.setText("Agregar");

        jBModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1426203706_sign-up.png"))); // NOI18N
        jBModificar.setText("Modificar");
        jBModificar.setEnabled(false);

        jBConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1426203891_Search-Male-User.png"))); // NOI18N
        jBConsultar.setText("Consultar");
        jBConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConsultarActionPerformed(evt);
            }
        });

        jBEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1426203830_Remove-Male-User.png"))); // NOI18N
        jBEliminar.setText("Eliminar");
        jBEliminar.setEnabled(false);

        jBSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1427101796_back.png"))); // NOI18N
        jBSalir.setText("Atras");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(JbAgregar)
                .addGap(18, 18, 18)
                .addComponent(jBModificar)
                .addGap(18, 18, 18)
                .addComponent(jBEliminar)
                .addGap(18, 18, 18)
                .addComponent(jBConsultar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(jBSalir)
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JbAgregar)
                    .addComponent(jBModificar)
                    .addComponent(jBEliminar)
                    .addComponent(jBConsultar)
                    .addComponent(jBSalir))
                .addContainerGap(72, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBConsultarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JbAgregar;
    private javax.swing.JButton jBConsultar;
    private javax.swing.JButton jBEliminar;
    private javax.swing.JButton jBModificar;
    private javax.swing.JButton jBSalir;
    // End of variables declaration//GEN-END:variables

    public static final String BTN_AGREGAR = "Agregar";
    public static final String BTN_MODIFICAR = "Modificar";
    public static final String BTN_ELIMINAR = "Eliminar";
    public static final String BTN_CONSULTAR = "Consultar";
    public static final String BTN_SALIR = "Atras";
    
    /**
     * 
     * @param controlador 
     */
    public void escuchar(ControlEstudiante controlador) {
        this.JbAgregar.addActionListener(controlador);
        this.jBConsultar.addActionListener(controlador);
        this.jBEliminar.addActionListener(controlador);
        this.jBModificar.addActionListener(controlador);
        this.jBSalir.addActionListener(controlador);
    }
    
    /**
     * 
     * @param estado 
     */
    public void enableButtons (boolean estado) {
        this.jBModificar.setEnabled(estado);
        this.jBEliminar.setEnabled(estado);
    }
}
