/**
 * panel reportes de la ventana GUIEReportesMatricula
 */
package vista;

import controlador.ControlReporteMatricula;

import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author vini
 */
public class PanelReporteMatricula extends javax.swing.JPanel {

    private String datos = "Nombre\t\tSiglas\tCreditos\n\n";

    /**
     * Creates new form PanelReporteMatricula
     */
    public PanelReporteMatricula() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldCarnerInforme = new javax.swing.JTextField();
        jButtonBuscarInforme = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelCarnet = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabelCantidadCursos = new javax.swing.JLabel();
        jLabelTotalCreditos = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButtonAtrasInforme = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabelEdad = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_Cursos_Matriculados = new javax.swing.JTable();

        setBackground(new java.awt.Color(164, 225, 178));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 3, 18)); // NOI18N
        jLabel1.setText("Informe de matricula");

        jLabel2.setFont(new java.awt.Font("Droid Sans Fallback", 1, 14)); // NOI18N
        jLabel2.setText("Ingrese el carnet:");

        jButtonBuscarInforme.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1426204169_xmag.png"))); // NOI18N
        jButtonBuscarInforme.setText("Buscar");
        jButtonBuscarInforme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarInformeActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Droid Sans Fallback", 3, 14)); // NOI18N
        jLabel3.setText("Datos del estudiante");

        jLabel4.setText("Nombre:");

        jLabel5.setText("Carnet:");

        jLabelNombre.setFont(new java.awt.Font("Droid Sans Fallback", 1, 13)); // NOI18N

        jLabelCarnet.setFont(new java.awt.Font("Droid Sans Fallback", 1, 13)); // NOI18N

        jLabel6.setText("Cantidad de cursos:");

        jLabel7.setText("Total de creditos matriculados");

        jLabelCantidadCursos.setFont(new java.awt.Font("Droid Sans Fallback", 1, 13)); // NOI18N

        jLabelTotalCreditos.setFont(new java.awt.Font("Droid Sans Fallback", 1, 13)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Droid Sans Fallback", 3, 13)); // NOI18N
        jLabel8.setText("Lista de cursos matriculados");

        jButtonAtrasInforme.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1427101796_back.png"))); // NOI18N
        jButtonAtrasInforme.setText("Atras");
        jButtonAtrasInforme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtrasInformeActionPerformed(evt);
            }
        });

        jLabel9.setText("Edad:");

        jLabelEdad.setFont(new java.awt.Font("Droid Sans Fallback", 1, 13)); // NOI18N

        jTable_Cursos_Matriculados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Siglas", "Creditos"
            }
        ));
        jScrollPane2.setViewportView(jTable_Cursos_Matriculados);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(275, 275, 275)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(652, 652, 652)
                        .addComponent(jButtonAtrasInforme))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabelNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabelCantidadCursos, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel5)
                                                    .addComponent(jLabel9))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jLabelCarnet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabelEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelTotalCreditos, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(464, 464, 464))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldCarnerInforme, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButtonBuscarInforme)
                                            .addComponent(jLabel8)))
                                    .addComponent(jLabel3))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldCarnerInforme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscarInforme))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabelNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5)
                                .addComponent(jLabelCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabelEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(53, 53, 53)
                                    .addComponent(jLabel6))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(53, 53, 53)
                                    .addComponent(jLabelCantidadCursos, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(20, 20, 20)
                            .addComponent(jLabel7))
                        .addComponent(jLabelTotalCreditos, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jButtonAtrasInforme)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAtrasInformeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtrasInformeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAtrasInformeActionPerformed

    private void jButtonBuscarInformeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarInformeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBuscarInformeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtrasInforme;
    private javax.swing.JButton jButtonBuscarInforme;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCantidadCursos;
    private javax.swing.JLabel jLabelCarnet;
    private javax.swing.JLabel jLabelEdad;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelTotalCreditos;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_Cursos_Matriculados;
    private javax.swing.JTextField jTextFieldCarnerInforme;
    // End of variables declaration//GEN-END:variables

    /**
     *
     * *************** metodos sets & gets ****************
     */
    public int getjLabelCantidadCursos() {
        return Integer.parseInt(jLabelCantidadCursos.toString().trim());
    }

    /**
     * 
     * @param jLabelCantidadCursos 
     */
    public void setjLabelCantidadCursos(int jLabelCantidadCursos) {
        if (jLabelCantidadCursos == 0) {
            this.jLabelCantidadCursos.setText("");
        } else {
            this.jLabelCantidadCursos.setText(jLabelCantidadCursos + "".trim());
        }
    }

    /**
     * 
     * ************ metodos sets & gets **************
     */
    public String getjLabelCarnet() {
        return jLabelCarnet.toString();
    }

    public void setjLabelCarnet(String jLabelCarnet) {
        this.jLabelCarnet.setText(jLabelCarnet);
    }

    public String getjLabelNombre() {
        return jLabelNombre.getText();
    }

    public void setjLabelNombre(String jLabelNombre) {
        this.jLabelNombre.setText(jLabelNombre);
    }

    public int getjLabelTotalCreditos() {
        return Integer.parseInt(jLabelTotalCreditos.toString().trim());
    }

    public void setjLabelTotalCreditos(int jLabelTotalCreditos) {
        if (jLabelTotalCreditos == 0) {
            this.jLabelTotalCreditos.setText("");
        } else {
            this.jLabelTotalCreditos.setText(jLabelTotalCreditos + "".trim());
        }
    }

    public String getjTextFieldCarnerInforme() {
        return jTextFieldCarnerInforme.getText();
    }

    public void setjTextFieldCarnerInforme(JTextField jTextFieldCarnerInforme) {
        this.jTextFieldCarnerInforme = jTextFieldCarnerInforme;
    }

    public String getjLabelEdad() {
        return jLabelEdad.getText();
    }

    public void setjLabelEdad(int jLabelEdad) {
        if (jLabelEdad == 0) {
            this.jLabelEdad.setText("");
        } else {
            this.jLabelEdad.setText(jLabelEdad + "".trim());
        }
    }

//////////////////////////////////////////////////////////////////////////////////
    public static final String JBTN_ATRAS_INFORME = "Atras";
    public static final String JBTN_BUSCAR_INFORME = "Buscar";

    /**
     *
     * @param control
     */
    public void escucharBotones(ControlReporteMatricula control) {
        this.jButtonAtrasInforme.addActionListener(control);
        this.jButtonBuscarInforme.addActionListener(control);
    }

    /**
     *
     */
    public void setTable(String[][] cursos, String[] etiquetas) {
        this.jTable_Cursos_Matriculados.setModel(new DefaultTableModel(cursos, etiquetas));
        this.jScrollPane2.setViewportView(jTable_Cursos_Matriculados);
    }

}
